name: Trivy Secret Scan

on:
  push:
    branches: [ "main" ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Trivy Secret Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scanners: secret
          exit-code: '1'
 
    
